# ===============================
# MYSQL DATABASE CONFIGURATION
# ===============================

spring.datasource.url=jdbc:mysql://localhost:3306/passwordmanager?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=kush@1923
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=8081

# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.tomcat.max-http-form-post-size=2MB
server.tomcat.max-swallow-size=2MB

# ===============================
# SERVER CONFIGURATION
# ===============================

server.port=8081